// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr3MV2Smk520C9g9sQK8PnSOm_C3lXXVg',
    appId: '1:31128110453:web:985555d49e2461d440ff3c',
    messagingSenderId: '31128110453',
    projectId: 'amnhac-e87b0',
    authDomain: 'amnhac-e87b0.firebaseapp.com',
    storageBucket: 'amnhac-e87b0.firebasestorage.app',
    measurementId: 'G-L0LXG7LZ7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSfvME2oEBinPrXgn4TnTqamAUUiF4K4Y',
    appId: '1:31128110453:android:26df14aa1853d5bf40ff3c',
    messagingSenderId: '31128110453',
    projectId: 'amnhac-e87b0',
    storageBucket: 'amnhac-e87b0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr3MV2Smk520C9g9sQK8PnSOm_C3lXXVg',
    appId: '1:31128110453:web:ea8c8f30e24362c540ff3c',
    messagingSenderId: '31128110453',
    projectId: 'amnhac-e87b0',
    authDomain: 'amnhac-e87b0.firebaseapp.com',
    storageBucket: 'amnhac-e87b0.firebasestorage.app',
    measurementId: 'G-76CSH2FBP3',
  );
}
